- name: Change host variable
  hosts: localhost
  connection: local
  tasks:
    - name: Use hostname from env var working_host
      ansible.builtin.add_host:
        name: "{{ working_host }}"
        groups: working_group
  tags:
    - always

- name: Create VM Template
  hosts: working_group
  gather_facts: true
  remote_user: root
  # become: true
  vars:
    ansible_roles_path: roles/
    # ansible_python_interpreter: /usr/bin/python
    ansible_ssh_port: 22

    # image_url: "http://download.proxmox.com/iso/proxmox-ve_7.4-1.iso"
    # image_name: "proxmox-ve.iso"

    # vm_memory: 10240
    # vm_cores: 4

  roles:
    - deploy_proxmox_on_hetzner
